name: CI

on:
  pull_request:
    branches: [ "main", "dev", "sprint-1" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: sage
          POSTGRES_PASSWORD: sage
          POSTGRES_DB: sage_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U sage"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: pytest -q --cov=api
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - run: |
          cd frontend
          pnpm install
          pnpm run build
